package org.cafe.views.budgets;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.cafe.database.controllers.BudgetController;
import org.cafe.database.controllers.BudgetItemController;
import org.cafe.models.budget.BudgetModel;
import org.cafe.utils.RecordVerificationUtil;
import org.cafe.utils.SearchFieldHandlerUtil;
import org.cafe.views.budget.BudgetView;
import org.cafe.views.budgets.components.manager_budget.ManagerBudgetView;

public class BudgetsView extends javax.swing.JFrame {
  private final BudgetController budgetController;
  private final BudgetItemController budgetItemController;
  private ArrayList<BudgetModel> budgets;

  /**
   * Construtor.
   *
   * @param budgetController Controlador de orçamentos.
   * @param budgetItemController Controlador de itens de orçamento.
   */
  public BudgetsView(
          BudgetController budgetController,
          BudgetItemController budgetItemController
  ) {
    this.budgetController = budgetController;
    this.budgetItemController = budgetItemController;

    initComponents();

    new SearchFieldHandlerUtil(searchField).initialize();

    listBudgets();
  }

  /**
   * Lista todos os orçamentos.
   */
  private void listBudgets() {
    budgets = budgetController.getAll();
    DefaultListModel<String> model = new DefaultListModel<>();
    budgetList.setModel(model);

    showBudgets(budgets);
  }

  /**
   * Mostra os itens repassados.
   */
  private void showBudgets(
          ArrayList<BudgetModel> value
  ) {
    DefaultListModel<String> model = new DefaultListModel<>();
    budgetList.setModel(model);

    for (BudgetModel budget : value) {
      String displayText = String.format("Nome: %s | Categoria: %s | Status: %s", budget.getName(), budget.getCategory(), budget.getStatus());

      model.addElement(displayText);
    }
  }

  /**
   * Atualiza a lista de orçamentos para exibir somente os orçamentos que
   * existem.
   */
  private void updateScreen() {
    DefaultListModel<String> model = new DefaultListModel<>();
    budgetList.setModel(model);
    model.clear();
    listBudgets();
  }

  /**
   * Método chamado quando um novo orçamento é criado.
   */
  private void onBudgetCreated(
          String budgetId
  ) {
    BudgetModel selectedBudget = budgetController.getById(budgetId);
    BudgetView budgetView = new BudgetView(budgetController, budgetItemController, selectedBudget, null);

    budgetView.setVisible(true);

    updateScreen();
  }

  private void onUpdateBudget(int index, BudgetModel value) {
    budgets.set(index, value);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    background = new javax.swing.JPanel();
    screenTitle = new javax.swing.JLabel();
    exitButton = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    budgetList = new javax.swing.JList<>();
    deleteButton = new javax.swing.JButton();
    updateButton = new javax.swing.JButton();
    addButton = new javax.swing.JButton();
    accessButton = new javax.swing.JButton();
    searchField = new javax.swing.JTextField();
    searchButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    background.setBackground(new java.awt.Color(255, 255, 255));

    screenTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    screenTitle.setForeground(new java.awt.Color(0, 0, 0));
    screenTitle.setText("Orçamentos");

    exitButton.setForeground(new java.awt.Color(255, 0, 51));
    exitButton.setText("Sair");
    exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        exitButtonMouseClicked(evt);
      }
    });

    budgetList.setBorder(null);
    jScrollPane1.setViewportView(budgetList);

    deleteButton.setForeground(new java.awt.Color(255, 0, 51));
    deleteButton.setText("Excluir");
    deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        deleteButtonMouseClicked(evt);
      }
    });

    updateButton.setText("Atualizar");
    updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        updateButtonMouseClicked(evt);
      }
    });

    addButton.setText("Adicionar");
    addButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        addButtonMouseClicked(evt);
      }
    });

    accessButton.setText("Acessar");
    accessButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        accessButtonMouseClicked(evt);
      }
    });

    searchButton.setText("S");
    searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        searchButtonMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
    background.setLayout(backgroundLayout);
    backgroundLayout.setHorizontalGroup(
      backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1)
      .addGroup(backgroundLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(backgroundLayout.createSequentialGroup()
            .addComponent(exitButton)
            .addGap(34, 34, 34)
            .addComponent(screenTitle)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
            .addComponent(addButton))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
            .addComponent(searchField)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(searchButton))
          .addGroup(backgroundLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(accessButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(updateButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(deleteButton)))
        .addContainerGap())
    );
    backgroundLayout.setVerticalGroup(
      backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(backgroundLayout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(screenTitle)
          .addComponent(exitButton)
          .addComponent(addButton))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(searchButton))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(deleteButton)
          .addComponent(updateButton)
          .addComponent(accessButton))
        .addContainerGap(244, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Ação de sair da tela.
   */
  private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
    this.dispose();
  }//GEN-LAST:event_exitButtonMouseClicked

  /**
   * Remove o orçamento selecionado.
   */
  private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
    if (RecordVerificationUtil.verifyRecords(budgetList, "excluir")) {
      // Confirmar remoção de registro.
      int confirm = JOptionPane.showConfirmDialog(
              null,
              "Você realmente deseja excluir este registro?",
              "Confirmar Exclusão",
              JOptionPane.YES_NO_OPTION,
              JOptionPane.WARNING_MESSAGE
      );

      // Se o usuário confirmar, exclui o registro.
      if (confirm == JOptionPane.YES_OPTION) {
        BudgetModel selectedExpense = budgets.get(budgetList.getSelectedIndex());
        budgetController.removeById(selectedExpense.getId());

        updateScreen();
      }
    }
  }//GEN-LAST:event_deleteButtonMouseClicked

  /**
   * Abre a tela de atualização de orçamento do orçamento selecionado.
   */
  private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
    if (RecordVerificationUtil.verifyRecords(budgetList, "atualizar")) {
      BudgetModel selectedBudget = budgets.get(budgetList.getSelectedIndex());
      ManagerBudgetView updateManagerBudgetView = new ManagerBudgetView(
              budgetController,
              selectedBudget,
              (budgetId) -> {
                updateScreen();
              }
      );

      updateManagerBudgetView.setVisible(true);
    }
  }//GEN-LAST:event_updateButtonMouseClicked

  /**
   * Abre a tela de criação de orçamento.
   */
  private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
    ManagerBudgetView createManagerBudgetView = new ManagerBudgetView(budgetController, null, this::onBudgetCreated);

    createManagerBudgetView.setVisible(true);
  }//GEN-LAST:event_addButtonMouseClicked

  /**
   * Abre a tela de orçamento do orçamento selecionado.
   */
  private void accessButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accessButtonMouseClicked
    if (RecordVerificationUtil.verifyRecords(budgetList, "acessar")) {
      BudgetModel selectedBudget = budgets.get(budgetList.getSelectedIndex());
      BudgetView budgetView = new BudgetView(
              budgetController,
              budgetItemController,
              selectedBudget,
              (value) -> {
                onUpdateBudget(budgetList.getSelectedIndex(), value);
              }
      );

      budgetView.setVisible(true);
    }
  }//GEN-LAST:event_accessButtonMouseClicked

  /**
   * Filtra os orçamento com base no nome e na descrição, baseado no texto
   * inserido na pesquisa.
   */
  private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
    String query = searchField.getText();

    if (query.equals("Pesquisar...")) {
      showBudgets(budgets);
    } else {
      ArrayList<BudgetModel> results = new ArrayList<>();

      for (BudgetModel budget : budgets) {
        if (budget.getName().contains(query) || budget.getDescription().contains(query)) {
          results.add(budget);
        }
      }

      showBudgets(results);
    }
  }//GEN-LAST:event_searchButtonMouseClicked

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton accessButton;
  private javax.swing.JButton addButton;
  private javax.swing.JPanel background;
  private javax.swing.JList<String> budgetList;
  private javax.swing.JButton deleteButton;
  private javax.swing.JLabel exitButton;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel screenTitle;
  private javax.swing.JButton searchButton;
  private javax.swing.JTextField searchField;
  private javax.swing.JButton updateButton;
  // End of variables declaration//GEN-END:variables
}
