package org.cafe.views.expenses.components.manager_expense;

import javax.swing.JOptionPane;
import org.cafe.database.controllers.ExpenseController;
import org.cafe.models.expense.CreateExpenseModel;
import org.cafe.models.expense.ExpenseModel;
import org.cafe.utils.NumberValidator;

public class ManagerExpenseView extends javax.swing.JFrame {
  private final Runnable onUpdateScreen;
  private final ExpenseController expenseController;
  private final ExpenseModel data;

  /**
   * Construtor.
   *
   * @param expenseController Controlador de despesas.
   * @param data Dados do registro selecionado caso seja para atualizar.
   * @param onUpdateScreen Função para atualização da tela de listagem das
   * despesas.
   */
  public ManagerExpenseView(ExpenseController expenseController, ExpenseModel data, Runnable onUpdateScreen) {
    this.expenseController = expenseController;
    this.data = data;
    this.onUpdateScreen = onUpdateScreen;

    initComponents();

    if (data != null) {
      nameField.setText(data.getName());
      descriptionField.setText(data.getDescription());
      valueField.setText(String.valueOf(data.getValue()));
      periodLabel.setText(data.getPeriod());

      screenTitle.setFocusable(true);
      screenTitle.setText("Atualizar Despesa");
      actionButton.setText("Atualizar");
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    background = new javax.swing.JPanel();
    screenTitle = new javax.swing.JLabel();
    nameLabel = new javax.swing.JLabel();
    nameField = new javax.swing.JTextField();
    valueField = new javax.swing.JTextField();
    valueLabell = new javax.swing.JLabel();
    descriptionField = new javax.swing.JTextField();
    descriptionLabel = new javax.swing.JLabel();
    actionButton = new javax.swing.JButton();
    calcelButton = new javax.swing.JButton();
    periodSelect = new javax.swing.JComboBox<>();
    periodLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    background.setBackground(new java.awt.Color(255, 255, 255));

    screenTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    screenTitle.setForeground(new java.awt.Color(0, 0, 0));
    screenTitle.setText("Criar Despesa");

    nameLabel.setBackground(new java.awt.Color(0, 0, 0));
    nameLabel.setForeground(new java.awt.Color(0, 0, 0));
    nameLabel.setText("Nome:");

    valueLabell.setBackground(new java.awt.Color(0, 0, 0));
    valueLabell.setForeground(new java.awt.Color(0, 0, 0));
    valueLabell.setText("Valor:");

    descriptionLabel.setBackground(new java.awt.Color(0, 0, 0));
    descriptionLabel.setForeground(new java.awt.Color(0, 0, 0));
    descriptionLabel.setText("Descrição:");

    actionButton.setText("Criar");
    actionButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        actionButtonMouseClicked(evt);
      }
    });

    calcelButton.setText("Cancelar");
    calcelButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        calcelButtonMouseClicked(evt);
      }
    });

    periodSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diário", "Semanal", "Mensal" }));

    periodLabel.setBackground(new java.awt.Color(0, 0, 0));
    periodLabel.setForeground(new java.awt.Color(0, 0, 0));
    periodLabel.setText("Periodicidade :");

    javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
    background.setLayout(backgroundLayout);
    backgroundLayout.setHorizontalGroup(
      backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
        .addContainerGap(147, Short.MAX_VALUE)
        .addComponent(screenTitle)
        .addGap(138, 138, 138))
      .addGroup(backgroundLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(descriptionField)
          .addComponent(nameField)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(calcelButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(actionButton))
          .addComponent(valueField)
          .addGroup(backgroundLayout.createSequentialGroup()
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(descriptionLabel)
              .addComponent(nameLabel)
              .addComponent(valueLabell)
              .addComponent(periodLabel)
              .addComponent(periodSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    backgroundLayout.setVerticalGroup(
      backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(backgroundLayout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addComponent(screenTitle)
        .addGap(30, 30, 30)
        .addComponent(nameLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(descriptionLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(valueLabell)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(valueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(periodLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(periodSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(actionButton)
          .addComponent(calcelButton))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Método chamado para sair da tela.
   */
    private void calcelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcelButtonMouseClicked
      this.dispose();
    }//GEN-LAST:event_calcelButtonMouseClicked

  /**
   * Método de criação ou atualização de uma despesa.
   */
    private void actionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionButtonMouseClicked
      String name = nameField.getText();
      String valueText = valueField.getText();
      String description = descriptionField.getText();

      if (name.isEmpty() || valueText.isEmpty() || description.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
      }

      NumberValidator numberValidator = new NumberValidator();
      if (!numberValidator.validate(this, valueText, "despesa")) {
        return;
      }

      String period = (String) periodSelect.getSelectedItem();

      if (data != null) {
        ExpenseModel expense = new ExpenseModel(data.getId(), name, numberValidator.getNumber(), period, description);
        expenseController.update(expense);
      } else {
        CreateExpenseModel expense = new CreateExpenseModel(name, numberValidator.getNumber(), period, description);
        expenseController.create(expense);
      }

      onUpdateScreen.run();

      this.dispose();
    }//GEN-LAST:event_actionButtonMouseClicked

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton actionButton;
  private javax.swing.JPanel background;
  private javax.swing.JButton calcelButton;
  private javax.swing.JTextField descriptionField;
  private javax.swing.JLabel descriptionLabel;
  private javax.swing.JTextField nameField;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JLabel periodLabel;
  private javax.swing.JComboBox<String> periodSelect;
  private javax.swing.JLabel screenTitle;
  private javax.swing.JTextField valueField;
  private javax.swing.JLabel valueLabell;
  // End of variables declaration//GEN-END:variables
}
