package org.cafe.views.main;

import java.util.ArrayList;
import org.cafe.database.controllers.BudgetController;
import org.cafe.database.controllers.BudgetItemController;
import org.cafe.database.controllers.ExpenseController;
import org.cafe.models.expense.ExpenseModel;
import org.cafe.utils.CurrencyFormatterUtil;
import org.cafe.views.budgets.BudgetsView;
import org.cafe.views.expenses.ExpensesView;

public class MainView extends javax.swing.JFrame {
  private final ExpenseController expenseController;
  private final BudgetController budgetController;
  private final BudgetItemController budgetItemController;

  /**
   * Construtor.
   *
   * @param expenseController Controlador de despesas.
   * @param budgetController Controlador de orçamentos.
   * @param budgetItemController Controlador de itens de orçamento.
   */
  public MainView(ExpenseController expenseController, BudgetController budgetController, BudgetItemController budgetItemController) {
    this.expenseController = expenseController;
    this.budgetController = budgetController;
    this.budgetItemController = budgetItemController;
    
    initComponents();
    
    int expensesAmountValue = 0;
    
    ArrayList<ExpenseModel> expenses = expenseController.getAll();
    for (ExpenseModel expense : expenses) {
      expensesAmountValue += expense.getValue();
    }
    
    String formattedValue = CurrencyFormatterUtil.format(expensesAmountValue);
    
    expensesAmount.setText(formattedValue);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    background = new javax.swing.JPanel();
    expenseField = new javax.swing.JDesktopPane();
    expenseTitle = new javax.swing.JLabel();
    expensesAmount = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    background.setBackground(new java.awt.Color(255, 255, 255));

    expenseField.setBackground(new java.awt.Color(255, 255, 255));
    expenseField.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        expenseFieldMouseClicked(evt);
      }
    });

    expenseTitle.setBackground(new java.awt.Color(0, 0, 0));
    expenseTitle.setForeground(new java.awt.Color(0, 0, 0));
    expenseTitle.setText("Despesas");

    expensesAmount.setBackground(new java.awt.Color(255, 0, 0));
    expensesAmount.setForeground(new java.awt.Color(255, 0, 0));
    expensesAmount.setText("R$ 2.000,00");

    expenseField.setLayer(expenseTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
    expenseField.setLayer(expensesAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout expenseFieldLayout = new javax.swing.GroupLayout(expenseField);
    expenseField.setLayout(expenseFieldLayout);
    expenseFieldLayout.setHorizontalGroup(
      expenseFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, expenseFieldLayout.createSequentialGroup()
        .addContainerGap(373, Short.MAX_VALUE)
        .addGroup(expenseFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(expensesAmount)
          .addComponent(expenseTitle))
        .addGap(19, 19, 19))
    );
    expenseFieldLayout.setVerticalGroup(
      expenseFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(expenseFieldLayout.createSequentialGroup()
        .addGap(127, 127, 127)
        .addComponent(expenseTitle)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(expensesAmount)
        .addContainerGap(176, Short.MAX_VALUE))
    );

    jButton1.setText("Acessar");
    jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton1MouseClicked(evt);
      }
    });

    javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
    background.setLayout(backgroundLayout);
    backgroundLayout.setHorizontalGroup(
      backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
        .addContainerGap(157, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addGap(76, 76, 76)
        .addComponent(expenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(25, 25, 25))
    );
    backgroundLayout.setVerticalGroup(
      backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(backgroundLayout.createSequentialGroup()
        .addGap(82, 82, 82)
        .addComponent(expenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(168, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addGap(270, 270, 270))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void expenseFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expenseFieldMouseClicked
      ExpensesView expenseView = new ExpensesView(expenseController);
      
      expenseView.setVisible(true);
    }//GEN-LAST:event_expenseFieldMouseClicked

  private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    BudgetsView budgetView = new BudgetsView(budgetController, budgetItemController);
    
    budgetView.setVisible(true);
  }//GEN-LAST:event_jButton1MouseClicked

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel background;
  private javax.swing.JDesktopPane expenseField;
  private javax.swing.JLabel expenseTitle;
  private javax.swing.JLabel expensesAmount;
  private javax.swing.JButton jButton1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
