
package org.cafe.views.main;
import java.util.ArrayList;
import org.cafe.database.controllers.BudgetController;
import org.cafe.database.controllers.BudgetItemController;
import org.cafe.database.controllers.ExpenseController;
import org.cafe.database.controllers.RevenueController;
import org.cafe.models.expense.ExpenseModel;
import org.cafe.models.revenue.RevenueModel;
import org.cafe.utils.CurrencyFormatterUtil;
import org.cafe.views.budgets.BudgetsView;
import org.cafe.views.expenses.ExpensesView;
import org.cafe.views.revenues.RevenueView;
import java.awt.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.*;


public class MainView extends javax.swing.JFrame {
  private final ExpenseController expenseController;
  private final RevenueController revenueController;
  private final BudgetController budgetController;
  private final BudgetItemController budgetItemController;
 /**
   * Construtor.
   *
   * @param expenseController Controlador de despesas.
     * @param revenueController Controlador de receitas.
   * @param budgetController Controlador de orçamentos.
   * @param budgetItemController Controlador de itens de orçamento.
   */
  public MainView(ExpenseController expenseController, RevenueController revenueController, BudgetController budgetController, BudgetItemController budgetItemController) {
    this.expenseController = expenseController;
    this.revenueController = revenueController;
    this.budgetController = budgetController;
    this.budgetItemController = budgetItemController;
    
    initComponents();
    
    int expensesAmountValue = 0;
    int revenuesAmountValue = 0;
    
    ArrayList<ExpenseModel> expenses = expenseController.getAll();
    for (ExpenseModel expense : expenses) {
      expensesAmountValue += expense.getValue();
    }
    
    ArrayList<RevenueModel> revenues = revenueController.getAll();
    for (RevenueModel revenue : revenues) {
      revenuesAmountValue += revenue.getValue();
    }
    graphicAdd();
    String formattedExpenseValue = CurrencyFormatterUtil.format(expensesAmountValue);
    String formattedRevenueValue = CurrencyFormatterUtil.format(revenuesAmountValue);
            
    
    expensesAmount.setText(formattedExpenseValue);
    revenuesAmount.setText(formattedRevenueValue);
  }
  
  private void graphicAdd() {
        // Criar os dados do gráfico
        PieDataset dataset = createDataset();

        
        // Criar o gráfico
        JFreeChart chart = ChartFactory.createPieChart(
                "",                   
                dataset,            
                false,                 
                true,                 
                false                 
        );

        // Criar o painel do gráfico
        ChartPanel chartPanel = new ChartPanel(chart);
        PiePlot plot = (PiePlot) chart.getPlot();
         plot.setOutlineVisible(false);
        chartPanel.setPreferredSize(new Dimension(400,250));
        chart.setBackgroundPaint(new Color(238,238,238,0)); 
        chart.getPlot().setBackgroundPaint(new Color(238,238,238,0)); 

        // Remover qualquer componente anterior e adicionar o gráfico ao painel
        graphicPanel.removeAll();
        graphicPanel.setLayout(new BorderLayout());
        graphicPanel.add(chartPanel, BorderLayout.CENTER);
        graphicPanel.revalidate();
        graphicPanel.repaint();
    }

    private PieDataset createDataset() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Despesas", expensesAmountValue);
        dataset.setValue("Receitas", revenuesAmountValue);
        return dataset;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        perfilButton = new javax.swing.JButton();
        jperfil = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        nameField = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cpfField = new javax.swing.JLabel();
        expenseField = new javax.swing.JDesktopPane();
        expenseTitle = new javax.swing.JLabel();
        expensesAmount = new javax.swing.JLabel();
        revenueField = new javax.swing.JDesktopPane();
        revenueTitle = new javax.swing.JLabel();
        revenuesAmount = new javax.swing.JLabel();
        budgetField = new javax.swing.JDesktopPane();
        budgetTitle = new javax.swing.JLabel();
        budgetAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(153, 0, 255));

        perfilButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        perfilButton.setText(" Butaom ");
        perfilButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jperfil.setBackground(new java.awt.Color(255, 255, 255));
        jperfil.setForeground(new java.awt.Color(255, 255, 255));
        jperfil.setText("Perfil");
        jperfil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        nameField.setText("Nome");
        nameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nameField))
        );

        cpfField.setText("Cpf");
        cpfField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cpfField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cpfField))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(perfilButton)
                .addGap(56, 56, 56))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addComponent(jperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perfilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        expenseField.setBackground(new java.awt.Color(153, 0, 255));
        expenseField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        expenseField.setForeground(new java.awt.Color(153, 51, 255));
        expenseField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expenseFieldMouseClicked(evt);
            }
        });

        expenseTitle.setBackground(new java.awt.Color(255, 255, 255));
        expenseTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        expenseTitle.setForeground(new java.awt.Color(255, 255, 255));
        expenseTitle.setText(" Despesas");

        expensesAmount.setBackground(new java.awt.Color(255, 255, 255));
        expensesAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        expensesAmount.setForeground(new java.awt.Color(255, 255, 255));
        expensesAmount.setText("  R$ 2.000,00");

        expenseField.setLayer(expenseTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        expenseField.setLayer(expensesAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout expenseFieldLayout = new javax.swing.GroupLayout(expenseField);
        expenseField.setLayout(expenseFieldLayout);
        expenseFieldLayout.setHorizontalGroup(
            expenseFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expenseFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(expenseFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expensesAmount)
                    .addGroup(expenseFieldLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(expenseTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        expenseFieldLayout.setVerticalGroup(
            expenseFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expenseFieldLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(expenseTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expensesAmount)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        revenueField.setBackground(new java.awt.Color(153, 0, 255));
        revenueField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        revenueField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                revenueFieldMouseClicked(evt);
            }
        });

        revenueTitle.setBackground(new java.awt.Color(0, 0, 0));
        revenueTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        revenueTitle.setForeground(new java.awt.Color(255, 255, 255));
        revenueTitle.setText(" Receitas");

        revenuesAmount.setBackground(new java.awt.Color(255, 255, 255));
        revenuesAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        revenuesAmount.setForeground(new java.awt.Color(255, 255, 255));
        revenuesAmount.setText("  R$ 2.000,00");

        revenueField.setLayer(revenueTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        revenueField.setLayer(revenuesAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout revenueFieldLayout = new javax.swing.GroupLayout(revenueField);
        revenueField.setLayout(revenueFieldLayout);
        revenueFieldLayout.setHorizontalGroup(
            revenueFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revenueFieldLayout.createSequentialGroup()
                .addGroup(revenueFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(revenueFieldLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(revenuesAmount))
                    .addGroup(revenueFieldLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(revenueTitle)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        revenueFieldLayout.setVerticalGroup(
            revenueFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revenueFieldLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(revenueTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(revenuesAmount)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        budgetField.setBackground(new java.awt.Color(153, 0, 255));
        budgetField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        budgetField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                budgetFieldMouseClicked(evt);
            }
        });

        budgetTitle.setBackground(new java.awt.Color(0, 0, 0));
        budgetTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        budgetTitle.setForeground(new java.awt.Color(255, 255, 255));
        budgetTitle.setText("Orçamento");

        budgetAmount.setBackground(new java.awt.Color(255, 255, 255));
        budgetAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        budgetAmount.setForeground(new java.awt.Color(255, 255, 255));
        budgetAmount.setText("  R$ 2.000,00");

        budgetField.setLayer(budgetTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        budgetField.setLayer(budgetAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout budgetFieldLayout = new javax.swing.GroupLayout(budgetField);
        budgetField.setLayout(budgetFieldLayout);
        budgetFieldLayout.setHorizontalGroup(
            budgetFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(budgetFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(budgetFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(budgetAmount)
                    .addComponent(budgetTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        budgetFieldLayout.setVerticalGroup(
            budgetFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(budgetFieldLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(budgetTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(budgetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(expenseField)
                    .addComponent(budgetField)
                    .addComponent(revenueField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(budgetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(expenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(revenueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void expenseFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expenseFieldMouseClicked
        ExpensesView expenseView = new ExpensesView(expenseController);
      
      expenseView.setVisible(true);
    }//GEN-LAST:event_expenseFieldMouseClicked

    private void revenueFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revenueFieldMouseClicked
        RevenueView revenueView = new RevenueView(revenueController);
      
      revenueView.setVisible(true);
    }//GEN-LAST:event_revenueFieldMouseClicked

    private void budgetFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_budgetFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_budgetFieldMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel budgetAmount;
    private javax.swing.JDesktopPane budgetField;
    private javax.swing.JLabel budgetTitle;
    private javax.swing.JLabel cpfField;
    private javax.swing.JDesktopPane expenseField;
    private javax.swing.JLabel expenseTitle;
    private javax.swing.JLabel expensesAmount;
    private javax.swing.JPanel graphicPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jperfil;
    private javax.swing.JLabel nameField;
    private javax.swing.JButton perfilButton;
    private javax.swing.JDesktopPane revenueField;
    private javax.swing.JLabel revenueTitle;
    private javax.swing.JLabel revenuesAmount;
    // End of variables declaration//GEN-END:variables
}

