package br.edu.ifpb.views.budget;

import br.edu.ifpb.database.controllers.BudgetDatabaseController;
import br.edu.ifpb.database.controllers.BudgetItemDatabaseController;
import br.edu.ifpb.models.budget.BudgetModel;
import java.util.function.Consumer;

public class BudgetView extends javax.swing.JFrame {
  private final BudgetController controller;

  /**
   * Construtor.
   *
   * @param budgetDatabaseController Controlador de orçamentos.
   * @param budgetItemDatabaseController Controlador de itens de orçamento.
   * @param budget Dados do registro selecionado.
   * @param onUpdateBudget Metódo para atualização do orçamento.
   */
  public BudgetView(
          BudgetDatabaseController budgetDatabaseController,
          BudgetItemDatabaseController budgetItemDatabaseController,
          BudgetModel budget,
          Consumer<BudgetModel> onUpdateBudget
  ) {
    initComponents();

    this.controller = new BudgetController(
            this,
            budgetDatabaseController,
            budgetItemDatabaseController,
            budget,
            onUpdateBudget,
            exitButton,
            screenTitle,
            searchField,
            nameText,
            categoryText,
            descriptionText,
            statusText,
            initialDateText,
            endDateText,
            valueMinFilterField,
            valueMaxFilterField,
            periodFilterField,
            monetaryInfoTable,
            budgetItemsTable
    );
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    background = new javax.swing.JPanel();
    deleteButton = new javax.swing.JButton();
    updateButton = new javax.swing.JButton();
    addButton = new javax.swing.JButton();
    descriptionLabel = new javax.swing.JLabel();
    categoryLabel = new javax.swing.JLabel();
    statusLabel = new javax.swing.JLabel();
    initialDateLabel = new javax.swing.JLabel();
    endDateLabel = new javax.swing.JLabel();
    itemsText = new javax.swing.JLabel();
    nameLabel = new javax.swing.JLabel();
    searchField = new javax.swing.JTextField();
    periodFilterLabel = new javax.swing.JLabel();
    periodFilterField = new javax.swing.JComboBox<>();
    valueMinFilterLabel = new javax.swing.JLabel();
    valueMinFilterField = new javax.swing.JTextField();
    valueMaxFilterLabel = new javax.swing.JLabel();
    valueMaxFilterField = new javax.swing.JTextField();
    separator = new javax.swing.JSeparator();
    jScrollPane2 = new javax.swing.JScrollPane();
    budgetItemsTable = new javax.swing.JTable();
    exitButton = new javax.swing.JLabel();
    screenTitle = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    monetaryInfoTable = new javax.swing.JTable();
    budgetFinancialSummaryLabel = new javax.swing.JLabel();
    searchButton = new javax.swing.JButton();
    clearFiltersButton = new javax.swing.JButton();
    nameText = new javax.swing.JLabel();
    descriptionText = new javax.swing.JLabel();
    categoryText = new javax.swing.JLabel();
    initialDateText = new javax.swing.JLabel();
    statusText = new javax.swing.JLabel();
    endDateText = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    background.setBackground(new java.awt.Color(255, 255, 255));

    deleteButton.setForeground(new java.awt.Color(255, 0, 51));
    deleteButton.setText("Excluir");
    deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        deleteButtonMouseClicked(evt);
      }
    });

    updateButton.setText("Atualizar");
    updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        updateButtonMouseClicked(evt);
      }
    });

    addButton.setText("Adicionar");
    addButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        addButtonMouseClicked(evt);
      }
    });

    descriptionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    descriptionLabel.setText("Descrição:");

    categoryLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    categoryLabel.setText("Categoria:");

    statusLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    statusLabel.setText("Status:");

    initialDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    initialDateLabel.setText("Data Inicial:");

    endDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    endDateLabel.setText("Data Final:");

    itemsText.setText("Itens:");

    nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    nameLabel.setText("Nome:");

    periodFilterLabel.setText("Período:");

    periodFilterField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Diário", "Semanal", "Mensal" }));

    valueMinFilterLabel.setText("Valor Mínimo:");

    valueMaxFilterLabel.setText("Valor Máximo:");

    separator.setForeground(new java.awt.Color(60, 63, 65));

    budgetItemsTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Nome", "Descrição", "Valor", "Período", "Criado em"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane2.setViewportView(budgetItemsTable);
    if (budgetItemsTable.getColumnModel().getColumnCount() > 0) {
      budgetItemsTable.getColumnModel().getColumn(0).setMinWidth(120);
      budgetItemsTable.getColumnModel().getColumn(0).setPreferredWidth(120);
      budgetItemsTable.getColumnModel().getColumn(0).setMaxWidth(120);
      budgetItemsTable.getColumnModel().getColumn(2).setMinWidth(88);
      budgetItemsTable.getColumnModel().getColumn(2).setPreferredWidth(88);
      budgetItemsTable.getColumnModel().getColumn(2).setMaxWidth(88);
      budgetItemsTable.getColumnModel().getColumn(3).setMinWidth(60);
      budgetItemsTable.getColumnModel().getColumn(3).setPreferredWidth(60);
      budgetItemsTable.getColumnModel().getColumn(3).setMaxWidth(60);
      budgetItemsTable.getColumnModel().getColumn(4).setMinWidth(68);
      budgetItemsTable.getColumnModel().getColumn(4).setPreferredWidth(68);
      budgetItemsTable.getColumnModel().getColumn(4).setMaxWidth(68);
    }

    exitButton.setForeground(new java.awt.Color(255, 0, 51));
    exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        exitButtonMouseClicked(evt);
      }
    });

    screenTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    screenTitle.setForeground(new java.awt.Color(0, 0, 0));
    screenTitle.setText("Orçamento");

    monetaryInfoTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Valor do Orçamento", "Valor Total dos Itens", "Valor Restante"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(monetaryInfoTable);

    budgetFinancialSummaryLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    budgetFinancialSummaryLabel.setText("Resumo Financeiro do Orçamento:");

    searchButton.setText("Filtrar");
    searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        searchButtonMouseClicked(evt);
      }
    });

    clearFiltersButton.setText("Limpar Filtros");
    clearFiltersButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        clearFiltersButtonMouseClicked(evt);
      }
    });

    nameText.setForeground(new java.awt.Color(102, 102, 102));
    nameText.setText("name");

    descriptionText.setForeground(new java.awt.Color(102, 102, 102));
    descriptionText.setText("description");

    categoryText.setForeground(new java.awt.Color(102, 102, 102));
    categoryText.setText("category");

    initialDateText.setForeground(new java.awt.Color(102, 102, 102));
    initialDateText.setText("initial_date");

    statusText.setForeground(new java.awt.Color(102, 102, 102));
    statusText.setText("status");

    endDateText.setForeground(new java.awt.Color(102, 102, 102));
    endDateText.setText("end_date");

    javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
    background.setLayout(backgroundLayout);
    backgroundLayout.setHorizontalGroup(
      backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(separator)
      .addGroup(backgroundLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(backgroundLayout.createSequentialGroup()
            .addComponent(searchField)
            .addContainerGap())
          .addGroup(backgroundLayout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
            .addContainerGap())
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(categoryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryText))
              .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(initialDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(initialDateText)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusText))
              .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(endDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endDateText)))
            .addGap(139, 139, 139))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jScrollPane2)
              .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                .addComponent(valueMinFilterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueMinFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(valueMaxFilterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueMaxFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(periodFilterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(periodFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
          .addGroup(backgroundLayout.createSequentialGroup()
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(screenTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearFiltersButton))
              .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(backgroundLayout.createSequentialGroup()
                    .addComponent(descriptionLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(descriptionText))
                  .addGroup(backgroundLayout.createSequentialGroup()
                    .addComponent(nameLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(nameText))
                  .addComponent(budgetFinancialSummaryLabel))
                .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
          .addGroup(backgroundLayout.createSequentialGroup()
            .addComponent(itemsText)
            .addGap(0, 0, Short.MAX_VALUE))))
    );
    backgroundLayout.setVerticalGroup(
      backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(backgroundLayout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(screenTitle)
            .addComponent(clearFiltersButton)
            .addComponent(searchButton)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(nameLabel)
          .addComponent(nameText))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(descriptionLabel)
          .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(categoryLabel)
          .addComponent(statusLabel)
          .addComponent(categoryText)
          .addComponent(statusText))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(initialDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(initialDateText))
          .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(endDateLabel)
            .addComponent(endDateText)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(budgetFinancialSummaryLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(itemsText)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(6, 6, 6)
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(valueMinFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(valueMaxFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(valueMinFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(valueMaxFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(periodFilterLabel)
          .addComponent(periodFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(deleteButton)
          .addComponent(updateButton)
          .addComponent(addButton))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Abre a tela de criação de um item de orçamento.
   */
  private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
    controller.addButton();
  }//GEN-LAST:event_addButtonMouseClicked

  /**
   * Abre a tela de atualização do item de orçamento selecionado.
   */
  private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
    controller.updateButton();
  }//GEN-LAST:event_updateButtonMouseClicked

  /**
   * Remove o item de orçamento selecionado.
   */
  private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
    controller.deleteButton();
  }//GEN-LAST:event_deleteButtonMouseClicked

  /**
   * Fecha a tela.
   */
  private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
    this.dispose();
  }//GEN-LAST:event_exitButtonMouseClicked

  /**
   * Filtra os itens de orçamento de acordo com os filtros definidos.
   */
  private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
    controller.search();
  }//GEN-LAST:event_searchButtonMouseClicked

  /**
   * Remove todos os filtros.
   */
  private void clearFiltersButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFiltersButtonMouseClicked
    controller.clearFilters();
  }//GEN-LAST:event_clearFiltersButtonMouseClicked

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addButton;
  private javax.swing.JPanel background;
  private javax.swing.JLabel budgetFinancialSummaryLabel;
  private javax.swing.JTable budgetItemsTable;
  private javax.swing.JLabel categoryLabel;
  private javax.swing.JLabel categoryText;
  private javax.swing.JButton clearFiltersButton;
  private javax.swing.JButton deleteButton;
  private javax.swing.JLabel descriptionLabel;
  private javax.swing.JLabel descriptionText;
  private javax.swing.JLabel endDateLabel;
  private javax.swing.JLabel endDateText;
  private javax.swing.JLabel exitButton;
  private javax.swing.JLabel initialDateLabel;
  private javax.swing.JLabel initialDateText;
  private javax.swing.JLabel itemsText;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable monetaryInfoTable;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JLabel nameText;
  private javax.swing.JComboBox<String> periodFilterField;
  private javax.swing.JLabel periodFilterLabel;
  private javax.swing.JLabel screenTitle;
  private javax.swing.JButton searchButton;
  private javax.swing.JTextField searchField;
  private javax.swing.JSeparator separator;
  private javax.swing.JLabel statusLabel;
  private javax.swing.JLabel statusText;
  private javax.swing.JButton updateButton;
  private javax.swing.JTextField valueMaxFilterField;
  private javax.swing.JLabel valueMaxFilterLabel;
  private javax.swing.JTextField valueMinFilterField;
  private javax.swing.JLabel valueMinFilterLabel;
  // End of variables declaration//GEN-END:variables
}
