package org.cafe.views.budget.components.manager_budget;

import java.text.SimpleDateFormat;
import java.util.Date;
import org.cafe.core.formatters.DateMaskFormatter;

public class ManagerBudgetView extends javax.swing.JFrame {

  /**
   * Construtor.
   */
  public ManagerBudgetView() {
    initComponents();

    new DateMaskFormatter().applyMask(initialDateField);
    new DateMaskFormatter().applyMask(endDateField);
    
    Date currentDate = new Date();
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
    initialDateField.setText(formatter.format(currentDate));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    background = new javax.swing.JPanel();
    screenTitle = new javax.swing.JLabel();
    nameLabel = new javax.swing.JLabel();
    nameField = new javax.swing.JTextField();
    valueField = new javax.swing.JTextField();
    valueLabell = new javax.swing.JLabel();
    descriptionField = new javax.swing.JTextField();
    descriptionLabel = new javax.swing.JLabel();
    actionButton = new javax.swing.JButton();
    calcelButton = new javax.swing.JButton();
    descriptionLabel1 = new javax.swing.JLabel();
    initialDateLabel = new javax.swing.JLabel();
    endDateLabel = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox<>();
    endDateField = new javax.swing.JFormattedTextField();
    initialDateField = new javax.swing.JFormattedTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    background.setBackground(new java.awt.Color(255, 255, 255));

    screenTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    screenTitle.setForeground(new java.awt.Color(0, 0, 0));
    screenTitle.setText("Criar Orçamento");

    nameLabel.setBackground(new java.awt.Color(0, 0, 0));
    nameLabel.setForeground(new java.awt.Color(0, 0, 0));
    nameLabel.setText("Nome:");

    valueLabell.setBackground(new java.awt.Color(0, 0, 0));
    valueLabell.setForeground(new java.awt.Color(0, 0, 0));
    valueLabell.setText("Descrição:");

    descriptionLabel.setBackground(new java.awt.Color(0, 0, 0));
    descriptionLabel.setForeground(new java.awt.Color(0, 0, 0));
    descriptionLabel.setText("Categoria:");

    actionButton.setText("Criar");
    actionButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        actionButtonMouseClicked(evt);
      }
    });

    calcelButton.setText("Cancelar");
    calcelButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        calcelButtonMouseClicked(evt);
      }
    });

    descriptionLabel1.setBackground(new java.awt.Color(0, 0, 0));
    descriptionLabel1.setForeground(new java.awt.Color(0, 0, 0));
    descriptionLabel1.setText("Status:");

    initialDateLabel.setBackground(new java.awt.Color(0, 0, 0));
    initialDateLabel.setForeground(new java.awt.Color(0, 0, 0));
    initialDateLabel.setText("Data Inicial:");

    endDateLabel.setBackground(new java.awt.Color(0, 0, 0));
    endDateLabel.setForeground(new java.awt.Color(0, 0, 0));
    endDateLabel.setText("Data Final:");

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rascunho", "Finalizado", "Negado", "Aprovado" }));

    javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
    background.setLayout(backgroundLayout);
    backgroundLayout.setHorizontalGroup(
      backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
        .addContainerGap(140, Short.MAX_VALUE)
        .addComponent(screenTitle)
        .addGap(120, 120, 120))
      .addGroup(backgroundLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(nameField)
          .addComponent(valueField)
          .addComponent(descriptionField)
          .addGroup(backgroundLayout.createSequentialGroup()
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(nameLabel)
              .addComponent(valueLabell)
              .addComponent(descriptionLabel)
              .addComponent(descriptionLabel1)
              .addComponent(initialDateLabel)
              .addComponent(endDateLabel)
              .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(calcelButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(actionButton))
          .addComponent(endDateField)
          .addComponent(initialDateField))
        .addContainerGap())
    );
    backgroundLayout.setVerticalGroup(
      backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(backgroundLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(screenTitle)
        .addGap(29, 29, 29)
        .addComponent(nameLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(valueLabell)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(valueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(descriptionLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(descriptionLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(initialDateLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(initialDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(endDateLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(endDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(actionButton)
          .addComponent(calcelButton))
        .addContainerGap(18, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void calcelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcelButtonMouseClicked
      this.dispose();
    }//GEN-LAST:event_calcelButtonMouseClicked

    private void actionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionButtonMouseClicked
      this.dispose();
    }//GEN-LAST:event_actionButtonMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ManagerBudgetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ManagerBudgetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ManagerBudgetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ManagerBudgetView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ManagerBudgetView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton actionButton;
  private javax.swing.JPanel background;
  private javax.swing.JButton calcelButton;
  private javax.swing.JTextField descriptionField;
  private javax.swing.JLabel descriptionLabel;
  private javax.swing.JLabel descriptionLabel1;
  private javax.swing.JFormattedTextField endDateField;
  private javax.swing.JLabel endDateLabel;
  private javax.swing.JFormattedTextField initialDateField;
  private javax.swing.JLabel initialDateLabel;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JTextField nameField;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JLabel screenTitle;
  private javax.swing.JTextField valueField;
  private javax.swing.JLabel valueLabell;
  // End of variables declaration//GEN-END:variables
}
